
module.exports = [
    { id: 1 ,
     author: "Pablo Picasso",
     text:"Everything you can imagine is real.",
    },

    { id: 2,
     author: "Dr. Seuss",
     text:"Sometimes the questions are complicated and the answers are simple.",
    },
    { id: 3 ,
     author: "George Bernard Shaw",
     text:"Life isn't about finding yourself. Life is about creating yourself.",
    },
    { id: 4 ,
     author: "Dr. Seuss",
     text:"Today you are You, that is truer than true. There is no one alive who is Youer than You.",
    },
    { id: 5 ,
     author: "Woody Allen",
     text:"I'm not afraid of death; I just don't want to be there when it happens.",
    },
    { id: 6 ,
     author: "Markus Zusak",
     text:"Sometimes people are beautiful.Not in looks. Not in what they say. Just in what they are.",
    },
    { id: 7 ,
     author: "Albert Einstein",
     text:"Life is like riding a bicycle. To keep your balance, you must keep moving.",
    },
    { id: 8 ,
     author: "John Green",
     text:"Some infinities are bigger than other infinities.",
    },
    { id: 9 ,
     author: "Bill Watterson",
     text:"Reality continues to ruin my life.",
    },
    { id: 10 ,
     author: "Stephen Chbosky",
     text:"Things change. And friends leave. Life doesn't stop for anybody.",
    },
 ];