
/* Problem 2: Even Fibonacci Numbers
--------------------------------------

Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. 

By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed n, 
find the sum of the even-valued terms.

*/

//-----------------------------------------------------------
function fiboEvenSum(n) {

  let fibonacciArray = [];
  
  fibonacciArray[0] = 1
  fibonacciArray[1] = 2;

  for (let i = 2; i <= n ; i++) {
    fibonacciArray[i] = fibonacciArray[i-1] + fibonacciArray[i-2];
    console.log("fibonacciArray[", i , "]",  fibonacciArray[i])
  }




  return true;
}


fiboEvenSum(10)